  /* 
  Sketch generated by the Arduino IoT Cloud Thing "PocketPath"
  https://create.arduino.cc/cloud/things/d1d45b98-b89e-46fe-b072-492ce1c64c67 

  Arduino IoT Cloud Properties description

  The following variables are automatically generated and updated when changes are made to the Thing properties

  float latitude;
  float longitude;
  int date;
  int time;

  Properties which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "allincludes.h"
#include "transmit.h"
#include "sleep.h"
#include "track.h"

void setup()
{
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  while(!Serial);
  
  //Setup cloud connection.
  cloudConnect();
  cloudDebug();
}

void loop()
{
  /*
    State 0: Sleeping
    State 1: Tracking
    State 3: Transmitting
  */
  int state = 2;
  File sensorData;
  String fileName;

  //Change states here according to buttons or whatever.
  
  switch (state)  
  {
  case 0: //Sleeping state. References Sleep.cpp
    wifiDisconnect();
    break;
  case 1: //Tracking State. References Tracking.cpp
    wifiDisconnect();
    state = 0; //Once done writing data to sd card, goto sleep.
    break;
  case 2: //Transmitting State. References Transmit.cpp
    Serial.println("Begin Transmit state.");
    if(!WiFiconnected()){
      wifiConnect();
      Serial.println("Connecting to cloud...");
    }
    testupdate();
    delay(1000);
    break;
  default:
    state = 0; //Put everything into sleep mode.
    break;
  }
}